### ISSUE TITLE
/code 命令不起作用

### ISSUE THREAD

**Issue by skyblue** [shellfly/aoi#2]
<img width="180" alt="image" src="https://user-images.githubusercontent.com/248937/228500932-d0bd7086-8995-4325-8ee6-14b000ddde9b.png">

**Comment by shellfly** [comment]
@skyblue 有一个/debug指令，可以看到api实际返回的消息，你打开一下再试试

**Comment by shellfly** [comment]
@skyblue 修复了，可以去release页面下载最新版，或者 `go install github.com/shellfly/aoi@v0.1.4`
